version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11112
      POSTGRES_DB: ws-lab4
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 11112
      DB_NAME: ws-lab4
    ports:
      - "8080:8080"
    depends_on:
      - db
